### ISSUE TITLE
Ability to manually add some channels to the generated list

### ISSUE THREAD

**Issue by Dnkhatri** [SCP002/m3u-gen-acestream#8]
Hi can we get the ability whitelist channels names we know to the generated list. Lets say I select the filter Sports and Eng as language. The generated list has 10-12 channels only as many of the other channels that should be marked Sports and English are maybe not marked properly. Currently I am generating the sport eng list and all the sports links then a script to check the other file to copy all the eng language channels that I know names of to add to that playlist.

**Comment by SCP002** [comment]
@Dnkhatri Hello, if I understand your problem correctly, it removes too much channels when you set `languagesFilter` to `eng`. This way it will keep only channels which have `eng` language set to them and reject any sport channels with unset language.
To keep sport channels with unset language you can try:

```yaml
  categoriesFilter:
  - "sport"

  categoriesFilterStrict: false

  languagesFilter:
  - "eng"
  - ""

  languagesFilterStrict: false
```

And then to refine output any further, set: `nameRxFilter` and `nameRxBlacklist` accordingly.

You may also use:

```yaml
  categoriesFilter:
  - "sport"
  - ""
```

On top of that and refine with `nameRxFilter` / `nameRxBlacklist`.
